name: Build and deploy project to GitHub Pages.

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install project dependencies with yarn.
        run: yarn install

      - name: Make project build.
        run: yarn build

      - name: Publish to gh-pages branch.
        run: sh ./.github/gh-pages/publish.sh
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
          MAINTANER_EMAIL: ${{ secrets.MAINTANER_EMAIL }}
